name: CraftLife
version: ${project.version}
main: br.com.craftlife.core.CraftLife
authors: [Brun0XP]
api-version: 1.13
description: An api for creating plugins for minecraft, contains frameworks like aikar acf and inventory flamework
website: www.craftlife.com.br
